# Example full config
# - name: name your config so other team members know what it does.
#   message: (required) add in a message for slack to watch
#   onlyChannel: #(required) add a channel id here i.e C034H2X55D4
#   introduction: reply with introduction text
#   solution: reply with solution
#   question: ask if resolved
#   ignoreIfContains: # (optional) add regex in here to check the message for that text if its true the bot will not reply
#     - tools.treatwell.net\/iglu
name: message

replies:
  - name: Common trouble shooting checks  
    message: rwg
    action: switch
    keyword1: turn on
    onlyChannel: C034H2X55D4
    introduction: "Introduction"
    solution: ":one:\n\n:two:\n\n:three:"
    question: "If your query was resolved please add a :white_check_mark: to your post."
    ignoreIfContains:
      - wants to know
