# Example full config
# - name: name your config so other team members know what it does.
#   message: (required) add in a message for slack to watch
#   onlyChannel: #(required) add a channel id here i.e C034H2X55D4
#   introduction: reply with introduction text
#   solution: reply with solution
#   question: ask if resolved
#   ignoreIfContains: # (optional) add regex in here to check the message for that text if its true the bot will not reply
#     - tools.treatwell.net\/iglu
name: message

replies:
  - name: RWG switch on 
    message: (rwg|bwg|reserve with google)
    action: (switch on|turn on|enable)
    onlyChannel: C034H2X55D4
    greeting: "Hey :wave: "
    introduction: ' To switch on *Reserve With Google* follow these steps... '
    solution: "\n\n:one:  Check that the venue is *live on the marketplace* and that they accept *pay at the venue* bookings.\n\n:two:  Add the Iglu link to this <http://www.example.com|*Google Sheet*>.\n\n:three:  Let the partner know that their request will be processed within 1 business day. :tada:"
    extraInformation: "You can learn more about Reserve With Google <http://www.example.com|here>"
    question: "Add a :white_check_mark: to your original message to mark your query as resolved."
    ignoreIfContains:
      - wants to know
    psTeamUsers: U035UDUM0H0
    reactionAdded: white_check_mark
    reaction1ToAdd: robot_face
    reaction2ToAdd: snowflake
    reactionAddedGreeting: 'Hey :wave: '
    reactionAddedReply: " Your request has been marked as complete. :white_check_mark:\n\n:question: If you have a follow up question, untick your message and a member of the team will get back to you."
    reactionRemovedReply: " We have reopened your request.\n\nSit tight and a member of the team will be with you shortly.\n\n"

  - name: RWG switch off  
    message: rwg
    action: (switch off|turn off|disable)
    onlyChannel: C034H2X55D4
    introduction: "Hello :wave: "
    solution: ":one:\n\n:two:\n\n:three:"
    question: "If your query was resolved please add a :white_check_mark: to your post."
    ignoreIfContains:
      - wants to know
    psTeamUsers: U035UDUM0H0

