# Single value blocks such as type: divider do not need a name.

name: message

replies:
  - name: Common trouble shooting checks
    message: hello
    reply: poop sticks is my fav game sport

  - name: Common trouble shooting checks 2
    message: hello my name is
    reply: poop sticks is my fav game

  - name: Saleforce link without iglu link
    message: treatwell.lightning.force.com
    reply: add an iglu link
    ignoreIfContains:
      - tools.treatwell.net\/iglu
      - tools.treatwell.net\/link
      - tools.treatwell.net\/erber
