# Example full config
# - name: name your config so other team mebers know what it does.
#   message: (required) add in a message for slack to watch
#   reply: (required) the bot will reply to this message
#   onlyChannel: #(required) add a channel id here i.e C034H2X55D4
#   ignoreIfContains: # (optional) add regex in here to check the message for that text if its true the bot will not reply
#     - tools.treatwell.net\/iglu
name: message

replies:
  - name: Common trouble shooting checks
    message: hello
    onlyChannel: C034H2X55D4
    reply: poop sticks is my fav game sport

  - name: Common trouble shooting checks 2
    message: hello my name is
    onlyChannel: C034H2X55D4
    reply: poop sticks is my fav game

  - name: Saleforce link without iglu link
    message: treatwell.lightning.force.com
    reply: add an iglu link
    onlyChannel: C034H2X55D4
    ignoreIfContains:
      - tools.treatwell.net\/iglu