#replies:
#  - name: Name of query 
#    message: (abc|abc|abc)
#    action: (abc|abc|abc)
#    onlyChannel: Channel ID
#    greeting: "Hey :wave: "
#    introduction: ' To switch on *name of query* follow these steps... '
#    solution: "\n\n:one:  \n\n:two:  \n\n:three:  Last step :tada:"
#    extraInformation: "You can learn more about *Name of query* <http://www.example.com|here>"
#    ifSolved: "Add a :white_check_mark: to your original message to mark your query as resolved."
#    ignoreIfContains:
#      - wants to know
#    psTeamUsers: PS Team User ID
#    reactionAdded: white_check_mark
#    reaction1ToAdd: robot_face
#    reaction2ToAdd: snowflake
#    reactionAddedGreeting: 'Hey :wave: '
#    reactionAddedReply: " Your request has been marked as complete. :white_check_mark:\n\n:question: If you have a follow up question, untick your message and a member of the team will get back to you."
#    reactionRemovedReply: "\n\nWe have reopened your request. Sit tight and a member of the team will be with you shortly.\n\n"
name: message

replies:
  - name: RWG switch on 
    message: (rwg|bwg|reserve with google)
    ifContains: (switch on|turn on|enable)
    onlyChannel: C034H2X55D4
    reply: "Hey :wave: "
    introduction: ' To switch on *Reserve With Google* follow these steps... '
    solution: "\n\n:one:  Check that the venue is *live on the marketplace* and that they accept *pay at the venue* bookings.\n\n:two:  Add the Iglu link to this <http://www.example.com|*Google Sheet*>.\n\n:three:  Let the partner know that their request will be processed within 1 business day. :tada:"
    extraInformation: "You can learn more about Reserve With Google <http://www.example.com|here>"
    isSolved: "Add a :white_check_mark: to your original message to mark your query as resolved."
    ignoreIfContains: ppc
    psTeamUsers: U035UDUM0H0
    reactionAdded: white_check_mark
    reaction1ToAdd: robot_face
    reaction2ToAdd: snowflake
    reactionAddedGreeting: 'Hey :wave: '
    reactionAddedReply: " Your request has been marked as complete. :white_check_mark:\n\n:question: If you have a follow up question, untick your message and a member of the team will get back to you."
    reactionRemovedGreeting: ':robot_face: Hello again '
    reactionRemovedReply: "\n\nWe have reopened your request, don't you worry. Sit tight and a member of the team will be with you shortly.\n\n"
    complete: "Fantastic! :tada: We have marked your query as resolved. If you have any follow up questions, feel free to click on the reopen button and a member of the team will get back to you."

  - name: RWG switch off 
    message: (rwg|bwg|reserve with google)
    ifContains: (switch off|turn off|disable)
    onlyChannel: C034H2X55D4
    reply: "Hey :wave: "
    introduction: ' To switch off *Reserve With Google* follow these steps... '
    solution: "\n\n:one:  Add the Iglu link to this <http://www.example.com|*Google Sheet*>.\n\n:two:  Let the partner know that their request will be processed within 1 business day. :tada:"
    extraInformation: "You can learn more about Reserve With Google <http://www.example.com|here>"
    isSolved: "Click *yes* to mark your query as resolved. If I misunderstood your request, please click *no* so I can learn and improve."
    ignoreIfContains:
    psTeamUsers: U035UDUM0H0
    reactionAdded: white_check_mark
    reaction1ToAdd: robot_face
    reaction2ToAdd: snowflake
    reactionAddedGreeting: 'Hey :wave: '
    reactionAddedReply: " Your request has been marked as complete. :white_check_mark:\n\n:question: If you have a follow up question, untick your message and a member of the team will get back to you."
    reactionRemovedGreeting: ':robot_face: Hello again '
    reactionRemovedReply: "\n\nWe have reopened your request, don't you worry. Sit tight and a member of the team will be with you shortly.\n\n"

# Link Listeners
  - name: Saleforce link without iglu link 
    message: (treatwell.lightning.force.com|treatwell2021.lightning.force.com)
    onlyChannel: C034H2X55D4
    reply: "Hello "
    introduction: " :wave: \n\nIt looks like you might have forgotten the Iglu link. Could you add that into the thread, please? :pray: \n\n Not everyone in the team has access to Salesforce. :see_no_evil: "
    ignoreIfContains: tools.treatwell.net\/iglu